#!/bin/bash

# Rebuild docker infrastructure

docker stop valeriapostgis

docker rm -v valeriapostgis

docker run -d -P --name valeriapostgis geographica/postgis:postgresql-9.3.5-postgis-2.1.7-gdal-1.11.2-patched

# Rebuild project

